spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/SOFTWARE
    username: 
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  #文件上传的配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

syq:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: SOFTWARE
    user-ttl: 7200000
    user-token-name: authentication
  wechat:
    appid:
    secret:


# server:
#   port: 6660

